description: >
  This is a sample executor using Docker and base Ubuntu.
docker:
  - image: 'cimg/base:<<parameters.tag>>'
parameters:
  tag:
    default: "2020.10"
    description: >
      Pick a specific circleci/base image variant:
      https://hub.docker.com/r/cimg/base/tags
    type: string
